issuer: https://token.actions.githubusercontent.com
subject_pattern: repo:shopwell/dive:.*
claim_pattern:
    workflow_ref: shopwell/dive/.github/workflows/release-please.yml@refs/heads/trunk

permissions:
    contents: write
    pull_requests: write
