issuer: https://token.actions.githubusercontent.com
subject: repo:shopwell-shop@329940059/dive@1388495665:ref:refs/heads/trunk
claim_pattern:
    workflow_ref: shopwell-shop/dive/.github/workflows/release-please.yml@refs/heads/trunk

permissions:
    contents: write
    pull_requests: write
